export default JSON.stringify(
      [
      {
        "id":2866,
        "date":"2021-02-16T18:20:10",
        "date_gmt":"2021-02-16T18:20:10",
        "guid":{
          "rendered":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/?post_type=galleries&#038;p=2866"
        },
        "modified":"2021-02-16T18:20:10",
        "modified_gmt":"2021-02-16T18:20:10",
        "slug":"test-gallery-2-which-has-a-much-longer-title-and-so-on-and-so-forth",
        "status":"publish",
        "type":"galleries",
        "link":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/galleries\/test-gallery-2-which-has-a-much-longer-title-and-so-on-and-so-forth\/",
        "title":{
          "rendered":"Test gallery #2 which has a much longer title and so on and so forth"
        },
        "template":"",
        "acf":{
          "photos":[
            {
              "photo":{
                "ID":2806,
                "id":2806,
                "title":"IMG_5387_Purple_WEB",
                "filename":"IMG_5387_Purple_WEB.jpg",
                "filesize":420302,
                "url":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_5387_Purple_WEB.jpg",
                "link":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/galleries\/test-gallery-2-which-has-a-much-longer-title-and-so-on-and-so-forth\/img_5387_purple_web\/",
                "alt":"",
                "author":"1",
                "description":"",
                "caption":"",
                "name":"img_5387_purple_web",
                "status":"inherit",
                "uploaded_to":2866,
                "date":"2021-02-16 14:49:36",
                "modified":"2021-02-16 18:20:10",
                "menu_order":0,
                "mime_type":"image\/jpeg",
                "type":"image",
                "subtype":"jpeg",
                "icon":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-includes\/images\/media\/default.png",
                "width":2000,
                "height":1333,
                "sizes":{
                  "thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_5387_Purple_WEB-150x150.jpg",
                  "thumbnail-width":150,
                  "thumbnail-height":150,
                  "medium":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_5387_Purple_WEB-300x200.jpg",
                  "medium-width":300,
                  "medium-height":200,
                  "medium_large":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_5387_Purple_WEB-768x512.jpg",
                  "medium_large-width":768,
                  "medium_large-height":512,
                  "large":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_5387_Purple_WEB-1024x682.jpg",
                  "large-width":1024,
                  "large-height":682,
                  "1536x1536":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_5387_Purple_WEB-1536x1024.jpg",
                  "1536x1536-width":1536,
                  "1536x1536-height":1024,
                  "2048x2048":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_5387_Purple_WEB.jpg",
                  "2048x2048-width":2000,
                  "2048x2048-height":1333,
                  "woocommerce_thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_5387_Purple_WEB-300x300.jpg",
                  "woocommerce_thumbnail-width":300,
                  "woocommerce_thumbnail-height":300,
                  "woocommerce_single":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_5387_Purple_WEB-600x400.jpg",
                  "woocommerce_single-width":600,
                  "woocommerce_single-height":400,
                  "woocommerce_gallery_thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_5387_Purple_WEB-100x100.jpg",
                  "woocommerce_gallery_thumbnail-width":100,
                  "woocommerce_gallery_thumbnail-height":100,
                  "shop_catalog":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_5387_Purple_WEB-300x300.jpg",
                  "shop_catalog-width":300,
                  "shop_catalog-height":300,
                  "shop_single":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_5387_Purple_WEB-600x400.jpg",
                  "shop_single-width":600,
                  "shop_single-height":400,
                  "shop_thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_5387_Purple_WEB-100x100.jpg",
                  "shop_thumbnail-width":100,
                  "shop_thumbnail-height":100
                }
              }
            },
            {
              "photo":{
                "ID":2813,
                "id":2813,
                "title":"IMG_8887_WEB",
                "filename":"IMG_8887_WEB.jpg",
                "filesize":411025,
                "url":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_8887_WEB.jpg",
                "link":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/galleries\/test-gallery-2-which-has-a-much-longer-title-and-so-on-and-so-forth\/img_8887_web\/",
                "alt":"",
                "author":"1",
                "description":"",
                "caption":"",
                "name":"img_8887_web",
                "status":"inherit",
                "uploaded_to":2866,
                "date":"2021-02-16 14:49:54",
                "modified":"2021-02-16 18:20:10",
                "menu_order":0,
                "mime_type":"image\/jpeg",
                "type":"image",
                "subtype":"jpeg",
                "icon":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-includes\/images\/media\/default.png",
                "width":2000,
                "height":1333,
                "sizes":{
                  "thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_8887_WEB-150x150.jpg",
                  "thumbnail-width":150,
                  "thumbnail-height":150,
                  "medium":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_8887_WEB-300x200.jpg",
                  "medium-width":300,
                  "medium-height":200,
                  "medium_large":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_8887_WEB-768x512.jpg",
                  "medium_large-width":768,
                  "medium_large-height":512,
                  "large":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_8887_WEB-1024x682.jpg",
                  "large-width":1024,
                  "large-height":682,
                  "1536x1536":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_8887_WEB-1536x1024.jpg",
                  "1536x1536-width":1536,
                  "1536x1536-height":1024,
                  "2048x2048":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_8887_WEB.jpg",
                  "2048x2048-width":2000,
                  "2048x2048-height":1333,
                  "woocommerce_thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_8887_WEB-300x300.jpg",
                  "woocommerce_thumbnail-width":300,
                  "woocommerce_thumbnail-height":300,
                  "woocommerce_single":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_8887_WEB-600x400.jpg",
                  "woocommerce_single-width":600,
                  "woocommerce_single-height":400,
                  "woocommerce_gallery_thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_8887_WEB-100x100.jpg",
                  "woocommerce_gallery_thumbnail-width":100,
                  "woocommerce_gallery_thumbnail-height":100,
                  "shop_catalog":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_8887_WEB-300x300.jpg",
                  "shop_catalog-width":300,
                  "shop_catalog-height":300,
                  "shop_single":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_8887_WEB-600x400.jpg",
                  "shop_single-width":600,
                  "shop_single-height":400,
                  "shop_thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/IMG_8887_WEB-100x100.jpg",
                  "shop_thumbnail-width":100,
                  "shop_thumbnail-height":100
                }
              }
            }
          ],
          "market":{
            "value":"single-family-hoa: Single Family\/HOA",
            "label":"single-family-hoa: Single Family\/HOA"
          },
          "featured":false
        },
        "_links":{
          "self":[
            {
              "href":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-json\/wp\/v2\/galleries\/2866"
            }
          ],
          "collection":[
            {
              "href":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-json\/wp\/v2\/galleries"
            }
          ],
          "about":[
            {
              "href":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-json\/wp\/v2\/types\/galleries"
            }
          ],
          "wp:attachment":[
            {
              "href":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-json\/wp\/v2\/media?parent=2866"
            }
          ],
          "curies":[
            {
              "name":"wp",
              "href":"https:\/\/api.w.org\/{rel}",
              "templated":true
            }
          ]
        }
      },
      {
        "id":2865,
        "date":"2021-02-16T18:18:34",
        "date_gmt":"2021-02-16T18:18:34",
        "guid":{
          "rendered":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/?post_type=galleries&#038;p=2865"
        },
        "modified":"2021-02-16T18:18:34",
        "modified_gmt":"2021-02-16T18:18:34",
        "slug":"test-gallery-1",
        "status":"publish",
        "type":"galleries",
        "link":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/galleries\/test-gallery-1\/",
        "title":{
          "rendered":"Test Gallery 1"
        },
        "template":"",
        "acf":{
          "featured":true,
          "photos":[
            {
              "photo":{
                "ID":2787,
                "id":2787,
                "title":"Quantum-Weighted-Dip-Assist-9.jpeg",
                "filename":"Quantum-Weighted-Dip-Assist-9.jpeg",
                "filesize":169604,
                "url":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Quantum-Weighted-Dip-Assist-9.jpeg",
                "link":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/?attachment_id=2787",
                "alt":"",
                "author":"1",
                "description":"",
                "caption":"",
                "name":"quantum-weighted-dip-assist-9-jpeg",
                "status":"inherit",
                "uploaded_to":2696,
                "date":"2021-02-10 17:59:16",
                "modified":"2021-02-10 17:59:16",
                "menu_order":0,
                "mime_type":"image\/jpeg",
                "type":"image",
                "subtype":"jpeg",
                "icon":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-includes\/images\/media\/default.png",
                "width":562,
                "height":750,
                "sizes":{
                  "thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Quantum-Weighted-Dip-Assist-9-150x150.jpeg",
                  "thumbnail-width":150,
                  "thumbnail-height":150,
                  "medium":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Quantum-Weighted-Dip-Assist-9-225x300.jpeg",
                  "medium-width":225,
                  "medium-height":300,
                  "medium_large":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Quantum-Weighted-Dip-Assist-9.jpeg",
                  "medium_large-width":562,
                  "medium_large-height":750,
                  "large":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Quantum-Weighted-Dip-Assist-9.jpeg",
                  "large-width":562,
                  "large-height":750,
                  "1536x1536":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Quantum-Weighted-Dip-Assist-9.jpeg",
                  "1536x1536-width":562,
                  "1536x1536-height":750,
                  "2048x2048":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Quantum-Weighted-Dip-Assist-9.jpeg",
                  "2048x2048-width":562,
                  "2048x2048-height":750,
                  "woocommerce_thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Quantum-Weighted-Dip-Assist-9-300x300.jpeg",
                  "woocommerce_thumbnail-width":300,
                  "woocommerce_thumbnail-height":300,
                  "woocommerce_single":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Quantum-Weighted-Dip-Assist-9.jpeg",
                  "woocommerce_single-width":562,
                  "woocommerce_single-height":750,
                  "woocommerce_gallery_thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Quantum-Weighted-Dip-Assist-9-100x100.jpeg",
                  "woocommerce_gallery_thumbnail-width":100,
                  "woocommerce_gallery_thumbnail-height":100,
                  "shop_catalog":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Quantum-Weighted-Dip-Assist-9-300x300.jpeg",
                  "shop_catalog-width":300,
                  "shop_catalog-height":300,
                  "shop_single":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Quantum-Weighted-Dip-Assist-9.jpeg",
                  "shop_single-width":562,
                  "shop_single-height":750,
                  "shop_thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Quantum-Weighted-Dip-Assist-9-100x100.jpeg",
                  "shop_thumbnail-width":100,
                  "shop_thumbnail-height":100
                }
              }
            },
            {
              "photo":{
                "ID":2770,
                "id":2770,
                "title":"Hammer-Strength-Decline-Press-1.jpeg",
                "filename":"Hammer-Strength-Decline-Press-1.jpeg",
                "filesize":155337,
                "url":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-Decline-Press-1.jpeg",
                "link":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/?attachment_id=2770",
                "alt":"",
                "author":"1",
                "description":"",
                "caption":"",
                "name":"hammer-strength-decline-press-1-jpeg",
                "status":"inherit",
                "uploaded_to":2673,
                "date":"2021-02-10 17:58:52",
                "modified":"2021-02-10 17:58:52",
                "menu_order":0,
                "mime_type":"image\/jpeg",
                "type":"image",
                "subtype":"jpeg",
                "icon":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-includes\/images\/media\/default.png",
                "width":562,
                "height":750,
                "sizes":{
                  "thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-Decline-Press-1-150x150.jpeg",
                  "thumbnail-width":150,
                  "thumbnail-height":150,
                  "medium":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-Decline-Press-1-225x300.jpeg",
                  "medium-width":225,
                  "medium-height":300,
                  "medium_large":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-Decline-Press-1.jpeg",
                  "medium_large-width":562,
                  "medium_large-height":750,
                  "large":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-Decline-Press-1.jpeg",
                  "large-width":562,
                  "large-height":750,
                  "1536x1536":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-Decline-Press-1.jpeg",
                  "1536x1536-width":562,
                  "1536x1536-height":750,
                  "2048x2048":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-Decline-Press-1.jpeg",
                  "2048x2048-width":562,
                  "2048x2048-height":750,
                  "woocommerce_thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-Decline-Press-1-300x300.jpeg",
                  "woocommerce_thumbnail-width":300,
                  "woocommerce_thumbnail-height":300,
                  "woocommerce_single":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-Decline-Press-1.jpeg",
                  "woocommerce_single-width":562,
                  "woocommerce_single-height":750,
                  "woocommerce_gallery_thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-Decline-Press-1-100x100.jpeg",
                  "woocommerce_gallery_thumbnail-width":100,
                  "woocommerce_gallery_thumbnail-height":100,
                  "shop_catalog":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-Decline-Press-1-300x300.jpeg",
                  "shop_catalog-width":300,
                  "shop_catalog-height":300,
                  "shop_single":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-Decline-Press-1.jpeg",
                  "shop_single-width":562,
                  "shop_single-height":750,
                  "shop_thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-Decline-Press-1-100x100.jpeg",
                  "shop_thumbnail-width":100,
                  "shop_thumbnail-height":100
                }
              }
            },
            {
              "photo":{
                "ID":2772,
                "id":2772,
                "title":"Hammer-Strength-High-Row-1.jpeg",
                "filename":"Hammer-Strength-High-Row-1.jpeg",
                "filesize":192120,
                "url":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-High-Row-1.jpeg",
                "link":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/?attachment_id=2772",
                "alt":"",
                "author":"1",
                "description":"",
                "caption":"",
                "name":"hammer-strength-high-row-1-jpeg",
                "status":"inherit",
                "uploaded_to":2674,
                "date":"2021-02-10 17:58:54",
                "modified":"2021-02-10 17:58:54",
                "menu_order":0,
                "mime_type":"image\/jpeg",
                "type":"image",
                "subtype":"jpeg",
                "icon":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-includes\/images\/media\/default.png",
                "width":562,
                "height":750,
                "sizes":{
                  "thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-High-Row-1-150x150.jpeg",
                  "thumbnail-width":150,
                  "thumbnail-height":150,
                  "medium":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-High-Row-1-225x300.jpeg",
                  "medium-width":225,
                  "medium-height":300,
                  "medium_large":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-High-Row-1.jpeg",
                  "medium_large-width":562,
                  "medium_large-height":750,
                  "large":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-High-Row-1.jpeg",
                  "large-width":562,
                  "large-height":750,
                  "1536x1536":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-High-Row-1.jpeg",
                  "1536x1536-width":562,
                  "1536x1536-height":750,
                  "2048x2048":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-High-Row-1.jpeg",
                  "2048x2048-width":562,
                  "2048x2048-height":750,
                  "woocommerce_thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-High-Row-1-300x300.jpeg",
                  "woocommerce_thumbnail-width":300,
                  "woocommerce_thumbnail-height":300,
                  "woocommerce_single":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-High-Row-1.jpeg",
                  "woocommerce_single-width":562,
                  "woocommerce_single-height":750,
                  "woocommerce_gallery_thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-High-Row-1-100x100.jpeg",
                  "woocommerce_gallery_thumbnail-width":100,
                  "woocommerce_gallery_thumbnail-height":100,
                  "shop_catalog":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-High-Row-1-300x300.jpeg",
                  "shop_catalog-width":300,
                  "shop_catalog-height":300,
                  "shop_single":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-High-Row-1.jpeg",
                  "shop_single-width":562,
                  "shop_single-height":750,
                  "shop_thumbnail":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-content\/uploads\/2021\/02\/Hammer-Strength-High-Row-1-100x100.jpeg",
                  "shop_thumbnail-width":100,
                  "shop_thumbnail-height":100
                }
              }
            }
          ],
          "market":{
            "value":"country-clubs: Country Clubs",
            "label":"country-clubs: Country Clubs"
          }
        },
        "_links":{
          "self":[
            {
              "href":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-json\/wp\/v2\/galleries\/2865"
            }
          ],
          "collection":[
            {
              "href":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-json\/wp\/v2\/galleries"
            }
          ],
          "about":[
            {
              "href":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-json\/wp\/v2\/types\/galleries"
            }
          ],
          "wp:attachment":[
            {
              "href":"https:\/\/innovativefitness.ahn2k5uj-liquidwebsites.com\/wp-json\/wp\/v2\/media?parent=2865"
            }
          ],
          "curies":[
            {
              "name":"wp",
              "href":"https:\/\/api.w.org\/{rel}",
              "templated":true
            }
          ]
        }
      }
    ]
);